#server
server:
  port: 8081
  tomcat:
    uri-encoding: utf-8

#spring
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ued?characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/

#mybatis
mybatis:
  type-aliases-package: com.sunlands.uedService.po

#cas
casServer: http://172.16.116.136:9091/cas
serverName: http://localhost:8081
ignoreAddress: /*|/*.html

